import '../scss/public.scss';
import '@fortawesome/fontawesome-free/css/all.min.css';
import "@fontsource/atkinson-hyperlegible/400.css";
import "@fontsource/atkinson-hyperlegible/700.css";
import "@fontsource/jetbrains-mono/500.css";
import { initStickyHeader } from './modules/sticky-header.js';
import { initDropdowns } from './modules/dropdowns.js';
import { initMobileNav } from './modules/mobile-nav.js';
import { initScrollReveal } from './modules/scroll-reveal.js';
import { initGallery } from "./public/community-gallery.js";
import { initCommunityAwardsFaq } from "./public/community-awards.js";
import { initAwardsNominationForm } from "./public/award-nomination.js";
import { initVotingFaq } from "./public/award-voting.js";
import { initWinnersFaq } from "./public/award-winners.js";
import { initAnimeAwards } from "./public/anime-awards.js";
import { initContactFaq } from "./public/contact.js";
import { initTriviaFaq } from "./public/trivia.js";
import { initLeaderboardFaq } from "./public/trivia-leaderboard.js";
import { initTriviaWinnersFaq } from "./public/trivia-winners.js";
import { initBlogHero } from "./public/blog.js";
import './public/honoured-ones.js';
import './public/auth/auth.js';
import './public/legals.js';

document.addEventListener('DOMContentLoaded', () => {
  initStickyHeader();
  initGallery();
  initCommunityAwardsFaq();
  initContactFaq();
  initAwardsNominationForm();
  initVotingFaq();
  initWinnersFaq();
  initTriviaWinnersFaq();
  initBlogHero();
  initLeaderboardFaq();
  initTriviaWinnersFaq();
  initAnimeAwards();
  initDropdowns();
  initMobileNav();
  initScrollReveal();
});

